# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_childwindows2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_content(object):
    def setupUi(self, select_content):
        select_content.setObjectName("select_content")
        select_content.resize(1051, 974)
        self.pushButton = QtWidgets.QPushButton(select_content)
        self.pushButton.setGeometry(QtCore.QRect(810, 930, 111, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(select_content)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 900, 900))
        self.textBrowser.setObjectName("textBrowser")
        self.label_heat = QtWidgets.QLabel(select_content)
        self.label_heat.setGeometry(QtCore.QRect(20, 20, 900, 900))
        self.label_heat.setText("")
        self.label_heat.setObjectName("label_heat")
        self.label_cbar = QtWidgets.QLabel(select_content)
        self.label_cbar.setGeometry(QtCore.QRect(940, 520, 91, 381))
        self.label_cbar.setText("")
        self.label_cbar.setObjectName("label_cbar")
        self.textBrowser.raise_()
        self.pushButton.raise_()
        self.label_heat.raise_()
        self.label_cbar.raise_()

        self.retranslateUi(select_content)
        QtCore.QMetaObject.connectSlotsByName(select_content)

    def retranslateUi(self, select_content):
        _translate = QtCore.QCoreApplication.translate
        select_content.setWindowTitle(_translate("select_content", "Errowarning"))
        self.pushButton.setText(_translate("select_content", "关闭"))
