# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_childwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_content(object):
    def setupUi(self, select_content):
        select_content.setObjectName("select_content")
        select_content.resize(608, 261)
        self.textBrowser = QtWidgets.QTextBrowser(select_content)
        self.textBrowser.setGeometry(QtCore.QRect(30, 20, 551, 191))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(select_content)
        self.pushButton.setGeometry(QtCore.QRect(480, 220, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(select_content)
        QtCore.QMetaObject.connectSlotsByName(select_content)

    def retranslateUi(self, select_content):
        _translate = QtCore.QCoreApplication.translate
        select_content.setWindowTitle(_translate("select_content", "Errowarning"))
        self.pushButton.setText(_translate("select_content", "确定"))
